### ISSUE TITLE
The API version used in the merchant-sdk is "117" and not the "124" (current)

### ISSUE THREAD

**Issue by adinath-raveendraraj** [paypal/merchant-sdk-java#33]
The SERVICE_VERSION variable in PayPalAPIInterfaceServiceService is set to "117.0", this value is sent as the PayPal API version in the SOAP request. Is there a reason that this value is not set to the current version of the API (which I understand is "124")?

**Comment by pp-randy** [comment]
This SDK is deprecated in favor of the REST SDK here: https://github.com/paypal/PayPal-Java-SDK. 117 is most likely the SOAP version the SDK was last updated for.  PayPal tries not to introduce breaking changes between SOAP versions so keeping it as 117 should help keep this SDK working longer since any new SOAP version could introduce wsdl changes this SDK can't handle.
